import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/use-toast";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Calendar,
  CalendarIcon,
  CheckCircle,
  ChevronDown,
  ClipboardList,
  Clock,
  Download,
  Edit,
  Eye,
  FileText,
  Filter,
  LineChart,
  Link,
  ListFilter,
  Loader,
  Package,
  PieChart,
  Plus,
  RefreshCw,
  Save,
  Search,
  Settings,
  Share,
  ShoppingCart,
  Sliders,
  Trash,
  Truck,
  Upload,
  Users,
  AlertCircle,
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  Bell,
  Calendar as CalendarIcon2,
  CheckSquare,
  ChevronUp,
  Copy,
  CreditCard,
  Database,
  DollarSign,
  EyeOff,
  FileBarChart,
  FileText2,
  Flag,
  Folder,
  FolderPlus,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Info,
  Layers,
  Layout,
  LifeBuoy,
  List,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize,
  Minimize,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointer,
  Move,
  Music,
  Navigation,
  Paperclip,
  Pause,
  Percent,
  Phone,
  Play,
  PlusCircle,
  PlusSquare,
  Pocket,
  Power,
  Printer,
  Radio,
  Repeat,
  RotateCcw,
  RotateCw,
  Rss,
  Scissors,
  Send,
  Server,
  Shield,
  ShieldOff,
  ShoppingBag,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slack,
  Slash,
  Smartphone,
  Speaker,
  Square,
  Star,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Tool,
  Trash2,
  TrendingDown,
  TrendingUp,
  Triangle,
  Tv,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Unlock,
  UploadCloud,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Video,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  X,
  XCircle,
  XOctagon,
  XSquare,
  Youtube,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
  Factory,
  Hammer,
  Cog,
  Wrench,
  Clipboard,
  Boxes,
  Box,
  Forklift,
  Conveyor,
  Warehouse,
  Recycle,
  Thermometer,
  Microscope,
  Beaker,
  Ruler,
  Scale,
  Droplet,
  Atom,
  Molecule,
  Dna,
  Virus,
  Bacteria,
  Pill,
  Capsule,
  Syringe,
  Vial,
  Flask,
  TestTube,
  Pipette,
  Centrifuge,
  Microscope2,
  Spectroscope,
  Chromatography,
  Distillation,
  Filtration,
  Extraction,
  Crystallization,
  Precipitation,
  Titration,
  Electrolysis,
  Fermentation,
  Polymerization,
  Catalysis,
  Oxidation,
  Reduction,
  Hydrolysis,
  Dehydration,
  Condensation,
  Substitution,
  Addition,
  Elimination,
  Rearrangement,
  Isomerization,
  Cyclization,
  Decyclization,
  Hydrogenation,
  Dehydrogenation,
  Halogenation,
  Dehalogenation,
  Nitration,
  Sulfonation,
  Amination,
  Diazotization,
  Esterification,
  Saponification,
  Alkylation,
  Acylation,
  Glycosylation,
  Phosphorylation,
  Methylation,
  Acetylation,
  Deacetylation,
  Demethylation,
  Dephosphorylation,
  Deglycosylation,
  Dealkylation,
  Deacylation,
  Gauge,
  Timer,
  AlertTriangle,
  Hourglass,
  CheckCircle2,
  PauseCircle,
  PlayCircle,
  Activity,
  Workflow,
} from "lucide-react";
import { Calendar as CalendarComponent } from "@/components/ui/calendar";
import {
  BarChart as RechartsBarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartsTooltip,
  Legend,
  ResponsiveContainer,
  LineChart as RechartsLineChart,
  Line,
  PieChart as RechartsPieChart,
  Pie,
  Cell,
  AreaChart,
  Area,
  ComposedChart,
  Scatter,
} from "recharts";
import { format, addDays, addMonths, isBefore, isAfter, parseISO } from "date-fns";
import { ar } from "date-fns/locale";

// Sample active production orders data
const activeProductionOrdersData = [
  {
    id: "PO-2024-001",
    product: "قميص قطني",
    quantity: 500,
    completedQuantity: 325,
    dueDate: "2024-08-15",
    status: "in-progress",
    progress: 65,
    workCenter: "قسم الخياطة",
    priority: "عالية",
    currentOperation: "خياطة القميص القطني",
    startDate: "2024-08-01",
    estimatedEndDate: "2024-08-12",
  },
  {
    id: "PO-2024-002",
    product: "بنطلون جينز",
    quantity: 300,
    completedQuantity: 0,
    dueDate: "2024-08-20",
    status: "planned",
    progress: 0,
    workCenter: "قسم القص",
    priority: "متوسطة",
    currentOperation: "قص قماش الجينز",
    startDate: "2024-08-05",
    estimatedEndDate: "2024-08-18",
  },
  {
    id: "PO-2024-004",
    product: "بلوزة حريرية",
    quantity: 150,
    completedQuantity: 45,
    dueDate: "2024-08-25",
    status: "in-progress",
    progress: 30,
    workCenter: "قسم التطريز",
    priority: "منخفضة",
    currentOperation: "تطريز البلوزة الحريرية",
    startDate: "2024-08-03",
    estimatedEndDate: "2024-08-22",
  },
  {
    id: "PO-2024-005",
    product: "جاكيت شتوي",
    quantity: 100,
    completedQuantity: 0,
    dueDate: "2024-09-05",
    status: "planned",
    progress: 0,
    workCenter: "قسم القص",
    priority: "متوسطة",
    currentOperation: "قص قماش الجاكيت",
    startDate: "2024-08-10",
    estimatedEndDate: "2024-09-02",
  },
];

// Sample work centers status data
const workCentersStatusData = [
  {
    id: "WC-001",
    name: "قسم القص",
    status: "active",
    currentOrders: 1,
    capacity: 3,
    utilization: 33,
    operators: 5,
    activeMachines: 3,
    totalMachines: 3,
    currentOperation: "قص قماش الجينز",
    nextOperation: "قص قماش الجاكيت",
    maintenanceScheduled: false,
  },
  {
    id: "WC-002",
    name: "قسم الخياطة",
    status: "active",
    currentOrders: 2,
    capacity: 3,
    utilization: 67,
    operators: 12,
    activeMachines: 7,
    totalMachines: 8,
    currentOperation: "خياطة القميص القطني",
    nextOperation: "خياطة بنطلون الجينز",
    maintenanceScheduled: false,
  },
  {
    id: "WC-003",
    name: "قسم التطريز",
    status: "active",
    currentOrders: 1,
    capacity: 2,
    utilization: 50,
    operators: 4,
    activeMachines: 2,
    totalMachines: 2,
    currentOperation: "تطريز البلوزة الحريرية",
    nextOperation: "تطريز القميص القطني",
    maintenanceScheduled: false,
  },
  {
    id: "WC-004",
    name: "قسم الكي",
    status: "idle",
    currentOrders: 0,
    capacity: 4,
    utilization: 0,
    operators: 6,
    activeMachines: 4,
    totalMachines: 4,
    currentOperation: "-",
    nextOperation: "كي القميص القطني",
    maintenanceScheduled: true,
  },
  {
    id: "WC-005",
    name: "قسم التعبئة",
    status: "idle",
    currentOrders: 0,
    capacity: 2,
    utilization: 0,
    operators: 8,
    activeMachines: 2,
    totalMachines: 2,
    currentOperation: "-",
    nextOperation: "تعبئة القميص القطني",
    maintenanceScheduled: false,
  },
];

// Sample active operations data
const activeOperationsData = [
